// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// obj
double obj(double l2, double lr, arma::mat Q, double dn, double YTY, arma::rowvec YTZ, arma::mat ZTZ, arma::colvec ZTY);
RcppExport SEXP _prolong_obj(SEXP l2SEXP, SEXP lrSEXP, SEXP QSEXP, SEXP dnSEXP, SEXP YTYSEXP, SEXP YTZSEXP, SEXP ZTZSEXP, SEXP ZTYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type l2(l2SEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type dn(dnSEXP);
    Rcpp::traits::input_parameter< double >::type YTY(YTYSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type YTZ(YTZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ZTZ(ZTZSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ZTY(ZTYSEXP);
    rcpp_result_gen = Rcpp::wrap(obj(l2, lr, Q, dn, YTY, YTZ, ZTZ, ZTY));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_prolong_obj", (DL_FUNC) &_prolong_obj, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_prolong(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
