# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

obj <- function(l2, lr, Q, dn, YTY, YTZ, ZTZ, ZTY) {
    .Call(`_prolong_obj`, l2, lr, Q, dn, YTY, YTZ, ZTZ, ZTY)
}

